import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { NosotrosComponent } from './nosotros/nosotros';
import { LoginComponent } from './login/login';
import { RegisterComponent } from './register/register.component';
import { DashboardEstudianteComponent } from './dashboard-estudiante/dashboard-estudiante';
import { DashboardProfesorComponent } from './dashboard-profesor/dashboard-profesor';
import { DashboardAdminComponent } from './dashboard-admin/dashboard-admin';
import { BlogComponent } from './blog.component/blog.component';
import { EvaluarComponent } from './evaluar/evaluar.component';
import { Temas } from './temas/temas';
import { TemaDetalleComponent } from './temas/tema-detalle/tema-detalle';
import { AnunciosComponent } from './anuncios/anuncios.component';
import { PreguntasComponent } from './preguntas/preguntas.component';
import { CursoDetalleComponent } from './cursos/curso-detalle.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'home', component: HomeComponent },
  { path: 'nosotros', component: NosotrosComponent },
  { path: 'evaluar', component: EvaluarComponent },
  { path: 'temas', component: Temas },
  { path: 'temas/:id', component: TemaDetalleComponent },
  { path: 'cursos/:slug', component: CursoDetalleComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'dashboard/estudiante', component: DashboardEstudianteComponent },
  { path: 'dashboard/profesor', component: DashboardProfesorComponent },
  { path: 'dashboard/admin', component: DashboardAdminComponent },
  { path: 'blog', component: BlogComponent },
  { path: 'anuncios', component: AnunciosComponent },
  { path: 'preguntas', component: PreguntasComponent },
];
