# Puerto de la API
server.port=8080

# Base de datos PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/proyecto_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres_password}
spring.jpa.hibernate.ddl-auto=${JPA_DDL:update}
spring.jpa.show-sql=true

# Seguridad - OAuth2 Resource Server

# La URL de donde Spring Security descarga la clave pública RSA para validar la firma
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/curso-springboot/protocol/openid-connect/certs}
